#!/usr/bin/env python3
"""Compiler-reflection census of module member visibility for geodesy-d.

Uses D's own __traits(allMembers, module) and __traits(getProtection, symbol)
rather than a source-text parser. The generated D source is compile-only and
emits machine-readable pragma(msg) records.

This establishes declared visibility of module members. It does not by itself
prove that every public name is usable through the package root, instantiate
templates, or certify complete callable signatures.
"""
import argparse
import csv
import re
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "source/geodesy/package.d"
IMPORT_RE = re.compile(r"^\s*public\s+import\s+(geodesy(?:\.[\w]+)+)\s*;", re.M)
MARKER = "__GEODESY_VIS__"
ROW_RE = re.compile(
    re.escape(MARKER) + r"\t(?P<module>[^\t\r\n]+)\t"
    r"(?P<name>[^\t\r\n]+)\t(?P<protection>[^\t\r\n]+)"
)


def exported_modules(package_text):
    modules = IMPORT_RE.findall(package_text)
    if len(modules) != len(set(modules)):
        raise ValueError("duplicate public imports in package.d")
    return modules


def generated_source(modules):
    all_modules = ["geodesy", *modules]
    out = [
        "// Generated by tools/research/compiler_visibility_census.py",
        "module geodesy_visibility_probe;",
    ]
    for i, module in enumerate(all_modules):
        out.append(f"import m{i} = {module};")
    out.append("")
    for i, module in enumerate(all_modules):
        # No declarations inside the static foreach body: avoids D declaration
        # collisions between iterations while still emitting one pragma per name.
        out.extend([
            f"static foreach (name; __traits(allMembers, m{i}))",
            "{",
            "    static if (__traits(compiles,",
            f"        __traits(getProtection, __traits(getMember, m{i}, name))))",
            "    {",
            f'        pragma(msg, "{MARKER}\\t{module}\\t" ~ name ~ "\\t" ~',
            f"            __traits(getProtection, __traits(getMember, m{i}, name)));",
            "    }",
            "    else",
            "    {",
            f'        pragma(msg, "{MARKER}\\t{module}\\t" ~ name ~ "\\tunresolved");',
            "    }",
            "}",
            "",
        ])
    return "\n".join(out)


def parse_records(text):
    rows = []
    seen = set()
    for m in ROW_RE.finditer(text):
        row = m.groupdict()
        key = (row["module"], row["name"], row["protection"])
        if key not in seen:
            seen.add(key)
            rows.append(row)
    return rows


def run_census(compiler, source):
    with tempfile.TemporaryDirectory(prefix="geodesy-visibility-") as tmp:
        path = Path(tmp) / "probe.d"
        path.write_text(source, encoding="utf-8")
        proc = subprocess.run(
            [compiler, "-o-", f"-I{ROOT / 'source'}", str(path)],
            cwd=ROOT, text=True, capture_output=True
        )
    output = (proc.stdout or "") + "\n" + (proc.stderr or "")
    rows = parse_records(output)
    if proc.returncode:
        raise RuntimeError(
            f"{compiler} reflection probe failed with exit {proc.returncode}:\n"
            + output[-4000:]
        )
    return rows


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--compiler", default="dmd")
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--source-output", type=Path)
    args = p.parse_args()

    modules = exported_modules(PACKAGE.read_text(encoding="utf-8"))
    if len(modules) != 28:
        raise SystemExit(f"unexpected root public import count: {len(modules)}")

    source = generated_source(modules)
    if args.source_output:
        args.source_output.parent.mkdir(parents=True, exist_ok=True)
        args.source_output.write_text(source, encoding="utf-8")

    rows = run_census(args.compiler, source)
    expected_modules = {"geodesy", *modules}
    observed_modules = {r["module"] for r in rows}
    missing = expected_modules - observed_modules
    if missing:
        raise SystemExit(f"reflection produced no records for modules: {sorted(missing)}")
    unresolved = [r for r in rows if r["protection"] == "unresolved"]
    if unresolved:
        raise SystemExit(f"unresolved reflection rows: {len(unresolved)}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["module", "name", "protection"])
        w.writeheader()
        w.writerows(sorted(rows, key=lambda r: (r["module"], r["name"], r["protection"])))

    counts = {}
    for row in rows:
        counts[row["protection"]] = counts.get(row["protection"], 0) + 1
    print(f"PASS: reflected {len(rows)} unique module-member visibility rows")
    print("Visibility counts:", dict(sorted(counts.items())))
    print("Modules:", len(observed_modules))
    print("Report:", args.output)


if __name__ == "__main__":
    main()
