#!/usr/bin/env python3
"""Generate 81 *concrete* external D calls from 27 public intersection overloads.

Calls are compiled, never executed; .init values are intentionally invalid
at runtime. No claims about convergence or numerical correctness are made.
"""
import argparse
import csv
import re
from pathlib import Path

from compare_overload_signatures import parts

FAMILIES = {
    "allGeodesicIntersections": 3,
    "closestGeodesicIntersection": 4,
    "nextGeodesicIntersection": 4,
    "tryAllGeodesicIntersections": 4,
    "tryClosestGeodesicIntersection": 8,
    "tryNextGeodesicIntersection": 4,
}


def parameters(signature, name):
    found = re.search(r"\b" + re.escape(name) + r"\s*\(\s*T\s*\)\s*\(", signature)
    if found is None:
        raise ValueError(f"Missing function-template parameter list: {signature}")
    start, depth = found.end(), 1
    for i in range(start, len(signature)):
        if signature[i] == "(":
            depth += 1
        elif signature[i] == ")":
            depth -= 1
            if depth == 0:
                return parts(signature[start:i])
    raise ValueError(f"Unbalanced: {signature}")


def parameter_type(raw):
    # The DDox token spacing is display syntax, not compilable D code.
    raw = re.sub(r"\s*!\s*", "!", raw)
    raw = re.sub(r"\s*\[\s*\]", "[]", raw)
    raw = re.sub(r"\s+", " ", raw).split(" = ", 1)[0].strip()
    raw = re.sub(r"^(ref|out|in)\s+", "", raw)
    typ, name = raw.rsplit(" ", 1)
    if not re.fullmatch(r"[A-Za-z_]\w*", name):
        raise ValueError(f"Unexpected parameter: {raw}")
    typ = re.sub(r"^const\s+", "", typ).replace(" ", "")
    if not re.fullmatch(r"[A-Za-z_][\w!\[\]]*", typ):
        raise ValueError(f"Unexpected parameter type: {typ}")
    return typ


def generate(rows):
    chosen = [r for r in rows if r["module"] == "geodesy.geodesic_intersection"
              and r["symbol"] in FAMILIES]
    counts = {k: sum(row["symbol"] == k for row in chosen) for k in FAMILIES}
    if counts != FAMILIES:
        raise ValueError(f"Expected exactly 27 public overloads: {counts}")
    out = ["// Generated by tools/research/generate_intersection_consumer.py",
           "// Compile only; never execute the deliberately .init-valued calls.",
           "module external_intersection_overload_calls;", "import geodesy;", ""]
    for scalar in ("float", "double", "real"):
        for row in chosen:
            name = row["symbol"]
            params = [parameter_type(x) for x in parameters(row["signature"], name)]
            out.extend([f"void probe_{name}_{row['overload']}_{scalar}() {{",
                        f"    alias T = {scalar};"])
            for index, typ in enumerate(params):
                out.append(f"    {typ} arg{index} = {typ}.init;")
            args = ", ".join(f"arg{i}" for i in range(len(params)))
            out.append(f"    auto result = {name}!T({args});")
            out.extend(["}", ""])
    out.append(f"// Generated {len(chosen) * 3} concrete calls.")
    return "\n".join(out) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("ddox_csv", type=Path)
    p.add_argument("output_d", type=Path)
    a = p.parse_args()
    with a.ddox_csv.open(encoding="utf-8", newline="") as f:
        text = generate(list(csv.DictReader(f)))
    a.output_d.parent.mkdir(parents=True, exist_ok=True)
    a.output_d.write_text(text, encoding="utf-8")
    print("PASS: generated", text.count("void probe_"), "concrete calls:", a.output_d)


if __name__ == "__main__":
    main()
